FROM python:3.12.9-slim

WORKDIR /app/gateway
RUN apt install uv
COPY ./pyproject.toml .
COPY ./uv.lock .
RUN uv sync --no-freeze
WORKDIR /app
COPY ../shared .

COPY . .
COPY ../shared .
CMD ["uv", "run", "uvicorn", "gateway.main:app", "--host", "0.0.0.0", "--port", "80", "--log-config", ".logging.yaml"]
